language: java
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN=:dd716e1b-eddb-43f0-9621-ce2702cd978a

before_script:
  - sudo apt-get install ant-optional
    